version: '3.7'

services:
    mariadb:
        image: mariadb
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - mariadb:/var/lib/mysql
            - ./script:/data
        expose:
            - 3306
        networks:
            - mon-reseau

    mysql-exporter:
        image: prom/mysqld-exporter
        restart: on-failure
        environment:
            DATA_SOURCE_NAME: "root:password@(mariadb:3306)/"
        expose:
            - 9104
        networks:
            - mon-reseau
            - exporter
        depends_on:
            - mariadb

    prometheus:
        image: prom/prometheus
        restart: on-failure
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        expose:
            - 9090
        ports:
            - "9090:9090"
        networks:
            - exporter
            - prometheus
        depends_on:
            - mysql-exporter

    grafana:
        image: grafana/grafana
        restart: on-failure
        volumes:
            - grafana:/var/lib/grafana
            - ./provisioning:/etc/grafana/provisioning
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: aled
            GF_USERS_ALLOW_SIGN_UP: "false"
        ports:
            - "3000:3000"
        networks:
            - prometheus
            - mon-reseau
        depends_on:
            - prometheus
            - mariadb

volumes:
    mariadb:
    grafana:

networks:
    mon-reseau:
    exporter:
    prometheus: