version:  '3.7'

services:
  maria-db1:
    image: mariadb:10.4
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mon-reseau
    volumes:
      - ./maria1:/var/lib/mysql
      - ./backups:/backups
      - ./config/master.cnf:/etc/mysql/mariadb.conf.d/master.cnf
      - ./scripts:/scripts

  maria-db2:
    image: mariadb:10.4
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mon-reseau
    volumes:
      - ./maria2:/var/lib/mysql
      - ./backups:/backups
      - ./config/slave.cnf:/etc/mysql/mariadb.conf.d/slave.cnf
      - ./scripts:/scripts

networks:
  mon-reseau: 
